name: "Dave's Blog"
favicon: null
layout_spectrum: 0.06471939175389707
typography_spectrum: 0.729526252951473
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5864264341071248
  lightness: 0.961713770404458
  saturation: 0.3156319905538112
  rhythmicContrast: 0.7395387159194797
purpose: []
