typography_spectrum: 0.729526252951473
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5864264341071248
  lightness: 0.961713770404458
  saturation: 0.3156319905538112
  rhythmicContrast: 0.7395387159194797
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.06471939175389707
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Dave
  email: dave.public@test.com
name: Dave's Blog
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
